<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DiscordControlCenter.Application\DiscordControlCenter.Application.csproj" />
    <ProjectReference Include="..\DiscordControlCenter.Core\DiscordControlCenter.Core.csproj" />
    <PackageReference Include="Discord.Net.WebSocket" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
